language: go

go:
  - master
  - 1.9.x
  - 1.10.x
  - 1.11.x

services:
  - mysql

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -v golang.org/x/lint/golint
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls
  - mysql -e 'CREATE DATABASE test_fixture;'

script:
  - dep init
  - dep ensure -v
  - go test -v -covermode=atomic -coverprofile=coverage.out -race
  - goveralls -coverprofile=coverage.out -service=travis-ci
